package danmuji

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

const metaGeneratedHeader = "// Code generated by danmuji — DO NOT EDIT.\n\n"

func TestMetaDanmujiSpecsCompileAndRun(t *testing.T) {
	repoRoot, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}

	specs, err := filepath.Glob(filepath.Join("testdata", "meta", "*.dmj"))
	if err != nil {
		t.Fatalf("glob meta specs: %v", err)
	}
	if len(specs) == 0 {
		t.Fatal("expected meta .dmj specs")
	}

	tmpDir := t.TempDir()
	goMod := fmt.Sprintf(`module danmuji_meta

go 1.24.0

require (
	github.com/odvcencio/danmuji v0.0.0
	github.com/stretchr/testify v1.9.0
)

replace github.com/odvcencio/danmuji => %s
`, repoRoot)
	if err := os.WriteFile(filepath.Join(tmpDir, "go.mod"), []byte(goMod), 0644); err != nil {
		t.Fatalf("write go.mod: %v", err)
	}

	for _, spec := range specs {
		source, err := os.ReadFile(spec)
		if err != nil {
			t.Fatalf("read %s: %v", spec, err)
		}

		goCode, err := TranspileDanmuji(source, TranspileOptions{
			SourceFile: filepath.Join(repoRoot, spec),
		})
		if err != nil {
			t.Fatalf("transpile %s: %v", spec, err)
		}

		name := strings.TrimSuffix(filepath.Base(spec), ".dmj")
		specDir := filepath.Join(tmpDir, name)
		if err := os.MkdirAll(specDir, 0755); err != nil {
			t.Fatalf("mkdir %s: %v", specDir, err)
		}

		outPath := filepath.Join(specDir, name+"_danmuji_test.go")
		output := metaGeneratedHeader + goCode
		if err := os.WriteFile(outPath, []byte(output), 0644); err != nil {
			t.Fatalf("write %s: %v", outPath, err)
		}
	}

	tidy := exec.Command("go", "mod", "tidy")
	tidy.Dir = tmpDir
	if out, err := tidy.CombinedOutput(); err != nil {
		t.Fatalf("go mod tidy: %v\n%s", err, out)
	}

	testCmd := exec.Command("go", "test", "-v", "./...")
	testCmd.Dir = tmpDir
	if out, err := testCmd.CombinedOutput(); err != nil {
		t.Fatalf("go test meta specs: %v\n%s", err, out)
	}
}
