// Package main implements the danmuji CLI tool that transpiles .dmj files
// to _danmuji_test.go files suitable for `go test`.
package main

import (
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/fsnotify/fsnotify"
	"github.com/odvcencio/danmuji"
)

const generatedHeader = "// Code generated by danmuji — DO NOT EDIT.\n\n"

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintf(os.Stderr, "Usage: danmuji <build|test> <path>\n")
		os.Exit(1)
	}

	switch os.Args[1] {
	case "build":
		debug, path := parseBuildArgs(os.Args[2:])
		if path == "" {
			fmt.Fprintf(os.Stderr, "Usage: danmuji build [--debug] <path>\n")
			os.Exit(1)
		}
		if err := build(path, debug); err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			os.Exit(1)
		}
	case "test":
		code := runTest(os.Args[2:])
		os.Exit(code)
	case "init":
		if err := initProject(); err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			os.Exit(1)
		}
	case "fmt":
		if len(os.Args) < 3 {
			fmt.Fprintf(os.Stderr, "Usage: danmuji fmt <path>\n")
			os.Exit(1)
		}
		if err := fmtDanmuji(os.Args[2]); err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			os.Exit(1)
		}
	default:
		fmt.Fprintf(os.Stderr, "Unknown command: %s\nUsage: danmuji <build|test|init|fmt> <path>\n", os.Args[1])
		os.Exit(1)
	}
}

// parseBuildArgs extracts --debug flag and path from build arguments.
func parseBuildArgs(args []string) (debug bool, path string) {
	for _, arg := range args {
		if arg == "--debug" {
			debug = true
		} else if path == "" {
			path = arg
		}
	}
	return
}

// transpileFile transpiles a single .dmj file and writes the output .go file.
// Returns the path to the generated file.
func transpileFile(path string, opts danmuji.TranspileOptions) (string, error) {
	source, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read %s: %w", path, err)
	}

	absPath, _ := filepath.Abs(path)
	opts.SourceFile = absPath
	goCode, err := danmuji.TranspileDanmuji(source, opts)
	if err != nil {
		return "", fmt.Errorf("transpile %s: %w", path, err)
	}

	// Output: foo_test.dmj -> foo_danmuji_test.go
	base := strings.TrimSuffix(filepath.Base(path), ".dmj")
	outName := base + "_danmuji_test.go"
	// If base already ends with _test, don't double it
	if strings.HasSuffix(base, "_test") {
		outName = strings.TrimSuffix(base, "_test") + "_danmuji_test.go"
	}
	outPath := filepath.Join(filepath.Dir(path), outName)

	output := generatedHeader + goCode
	if err := os.WriteFile(outPath, []byte(output), 0644); err != nil {
		return "", fmt.Errorf("write %s: %w", outPath, err)
	}

	fmt.Printf("  %s -> %s\n", filepath.Base(path), outName)
	return outPath, nil
}

func build(path string, debug bool) error {
	info, err := os.Stat(path)
	if err != nil {
		return err
	}

	opts := danmuji.TranspileOptions{Debug: debug}
	if info.IsDir() {
		return buildDir(path, opts)
	}
	_, err = transpileFile(path, opts)
	return err
}

func buildDir(dir string, opts danmuji.TranspileOptions) error {
	files, err := collectDanmujiFiles(dir)
	if err != nil {
		return err
	}

	generated, err := transpileFiles(files, opts)
	if err != nil {
		return err
	}
	fmt.Printf("danmuji: transpiled %d file(s)\n", len(generated))
	return nil
}

func collectDanmujiFiles(dir string) ([]string, error) {
	var files []string
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if strings.HasSuffix(d.Name(), ".dmj") {
			files = append(files, path)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(files)
	return files, nil
}

func transpileFiles(paths []string, opts danmuji.TranspileOptions) ([]string, error) {
	var generated []string
	var failures []string

	for _, path := range paths {
		outPath, err := transpileFile(path, opts)
		if err != nil {
			failures = append(failures, err.Error())
			continue
		}
		generated = append(generated, outPath)
	}

	if len(failures) > 0 {
		return generated, fmt.Errorf("%d file(s) failed to transpile:\n%s", len(failures), strings.Join(failures, "\n"))
	}

	return generated, nil
}

// runTest implements `danmuji test [--watch] <path> [-- go-test-flags...]`.
// It transpiles .dmj files, runs `go test`, cleans up generated files, and
// returns the exit code from `go test`.
func runTest(args []string) int {
	// Split args at "--" to separate danmuji args from go test flags.
	var path string
	var goTestFlags []string
	watch := false
	dashDash := -1
	for i, arg := range args {
		if arg == "--" {
			dashDash = i
			break
		}
	}
	if dashDash >= 0 {
		goTestFlags = args[dashDash+1:]
		args = args[:dashDash]
	}
	// Extract --watch flag
	var filteredArgs []string
	for _, arg := range args {
		if arg == "--watch" {
			watch = true
		} else {
			filteredArgs = append(filteredArgs, arg)
		}
	}
	args = filteredArgs
	if len(args) < 1 {
		fmt.Fprintf(os.Stderr, "Usage: danmuji test [--watch] <path> [-- go-test-flags...]\n")
		return 1
	}
	path = args[0]

	if watch {
		return watchAndTest(path, goTestFlags)
	}

	var dmjFiles []string
	info, err := os.Stat(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return 1
	}
	if info.IsDir() {
		dmjFiles, err = collectDanmujiFiles(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			return 1
		}
	} else {
		dmjFiles = append(dmjFiles, path)
	}

	if len(dmjFiles) == 0 {
		fmt.Fprintf(os.Stderr, "danmuji test: no .dmj files found at %s\n", path)
		return 1
	}

	// Transpile all .dmj files, collecting generated paths for cleanup.
	generated, err := transpileFiles(dmjFiles, danmuji.TranspileOptions{})
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		cleanup(generated)
		return 1
	}

	// Determine the directory to run `go test` in.
	testDir := path
	if !info.IsDir() {
		testDir = filepath.Dir(path)
	}

	// Run go test, streaming output to the terminal.
	goArgs := []string{"test"}
	goArgs = append(goArgs, goTestFlags...)
	if info.IsDir() {
		goArgs = append(goArgs, "./...")
	} else {
		goArgs = append(goArgs, ".")
	}
	cmd := exec.Command("go", goArgs...)
	cmd.Dir = testDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	exitCode := 0
	if err := cmd.Run(); err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			exitCode = exitErr.ExitCode()
		} else {
			fmt.Fprintf(os.Stderr, "error running go test: %v\n", err)
			exitCode = 1
		}
	}

	// Clean up generated files regardless of pass/fail.
	cleanup(generated)
	return exitCode
}

// watchAndTest watches for .dmj file changes and re-runs tests on each change.
func watchAndTest(path string, goTestFlags []string) int {
	// Resolve the watch directory.
	info, err := os.Stat(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return 1
	}
	watchDir := path
	if !info.IsDir() {
		watchDir = filepath.Dir(path)
	}

	watcher, err := fsnotify.NewWatcher()
	if err != nil {
		fmt.Fprintf(os.Stderr, "error creating watcher: %v\n", err)
		return 1
	}
	defer watcher.Close()

	if info.IsDir() {
		if err := addWatchDirs(watcher, watchDir); err != nil {
			fmt.Fprintf(os.Stderr, "error watching %s: %v\n", watchDir, err)
			return 1
		}
	} else {
		if err := watcher.Add(watchDir); err != nil {
			fmt.Fprintf(os.Stderr, "error watching %s: %v\n", watchDir, err)
			return 1
		}
	}

	fmt.Printf("danmuji: watching %s for changes (ctrl+c to stop)\n", watchDir)

	// Run once immediately.
	runTestOnce(path, goTestFlags)

	// Debounce: wait for events to settle before re-running.
	var debounce *time.Timer
	for {
		select {
		case event, ok := <-watcher.Events:
			if !ok {
				return 0
			}
			if event.Op&fsnotify.Create != 0 {
				if created, err := os.Stat(event.Name); err == nil && created.IsDir() {
					_ = addWatchDirs(watcher, event.Name)
					continue
				}
			}
			if !strings.HasSuffix(event.Name, ".dmj") {
				continue
			}
			if event.Op&(fsnotify.Write|fsnotify.Create|fsnotify.Remove|fsnotify.Rename) == 0 {
				continue
			}
			// Debounce: reset timer on each event, run after 200ms of quiet.
			if debounce != nil {
				debounce.Stop()
			}
			debounce = time.AfterFunc(200*time.Millisecond, func() {
				fmt.Printf("\n--- %s changed ---\n\n", filepath.Base(event.Name))
				runTestOnce(path, goTestFlags)
			})
		case err, ok := <-watcher.Errors:
			if !ok {
				return 0
			}
			fmt.Fprintf(os.Stderr, "watch error: %v\n", err)
		}
	}
}

func addWatchDirs(watcher *fsnotify.Watcher, root string) error {
	return filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return watcher.Add(path)
		}
		return nil
	})
}

// runTestOnce runs a single test cycle (transpile, go test, cleanup).
func runTestOnce(path string, goTestFlags []string) {
	// Build args for runTest (without --watch to avoid recursion).
	args := []string{path}
	if len(goTestFlags) > 0 {
		args = append(args, "--")
		args = append(args, goTestFlags...)
	}
	code := runTest(args)
	if code == 0 {
		fmt.Println("\n--- PASS ---")
	} else {
		fmt.Println("\n--- FAIL ---")
	}
}

// cleanup removes the given list of generated files, logging any errors.
func cleanup(files []string) {
	for _, f := range files {
		if err := os.Remove(f); err != nil && !os.IsNotExist(err) {
			fmt.Fprintf(os.Stderr, "warning: failed to clean up %s: %v\n", f, err)
		}
	}
}

// initProject adds testify to the current module.
func initProject() error {
	get := exec.Command("go", "get", "github.com/stretchr/testify@latest")
	get.Stdout = os.Stdout
	get.Stderr = os.Stderr
	if err := get.Run(); err != nil {
		return fmt.Errorf("go get testify: %w", err)
	}

	tidy := exec.Command("go", "mod", "tidy")
	tidy.Stdout = os.Stdout
	tidy.Stderr = os.Stderr
	if err := tidy.Run(); err != nil {
		return fmt.Errorf("go mod tidy: %w", err)
	}

	fmt.Println("danmuji: testify added. You're ready to write .dmj files.")
	return nil
}

// fmtDanmuji formats .dmj files with canonical indentation.
func fmtDanmuji(path string) error {
	info, err := os.Stat(path)
	if err != nil {
		return err
	}

	if info.IsDir() {
		files, err := collectDanmujiFiles(path)
		if err != nil {
			return err
		}
		for _, file := range files {
			if err := fmtFile(file); err != nil {
				return err
			}
		}
		fmt.Printf("danmuji fmt: formatted %d file(s)\n", len(files))
		return nil
	}
	return fmtFile(path)
}

func fmtFile(path string) error {
	source, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}

	formatted, err := danmuji.FormatDanmuji(source)
	if err != nil {
		return fmt.Errorf("format %s: %w", path, err)
	}

	if formatted == string(source) {
		return nil // already formatted
	}

	if err := os.WriteFile(path, []byte(formatted), 0644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	fmt.Printf("  %s\n", filepath.Base(path))
	return nil
}
