package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

var sharedTestModuleDir string

func TestMain(m *testing.M) {
	dir, err := prepareSharedTestModule()
	if err != nil {
		fmt.Fprintf(os.Stderr, "prepare shared test module: %v\n", err)
		os.Exit(1)
	}
	sharedTestModuleDir = dir

	code := m.Run()
	_ = os.RemoveAll(dir)
	os.Exit(code)
}

func prepareSharedTestModule() (string, error) {
	tmpDir, err := os.MkdirTemp("", "danmuji-cli-testmod-")
	if err != nil {
		return "", err
	}

	goMod := `module testpkg

go 1.24.0

require github.com/stretchr/testify v1.9.0
`
	if err := os.WriteFile(filepath.Join(tmpDir, "go.mod"), []byte(goMod), 0644); err != nil {
		return "", err
	}

	placeholder := `package testpkg_test

import _ "github.com/stretchr/testify/assert"
`
	placeholderPath := filepath.Join(tmpDir, "placeholder_test.go")
	if err := os.WriteFile(placeholderPath, []byte(placeholder), 0644); err != nil {
		return "", err
	}

	cmd := exec.Command("go", "mod", "tidy")
	cmd.Dir = tmpDir
	if out, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("go mod tidy: %w\n%s", err, out)
	}

	if err := os.Remove(placeholderPath); err != nil {
		return "", err
	}
	return tmpDir, nil
}

func newTestModule(t *testing.T) string {
	t.Helper()
	tmpDir := t.TempDir()
	for _, name := range []string{"go.mod", "go.sum"} {
		data, err := os.ReadFile(filepath.Join(sharedTestModuleDir, name))
		if err != nil {
			t.Fatalf("read shared %s: %v", name, err)
		}
		if err := os.WriteFile(filepath.Join(tmpDir, name), data, 0644); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}
	return tmpDir
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatalf("mkdir %s: %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func TestParseBuildArgs(t *testing.T) {
	debug, path := parseBuildArgs([]string{"--debug", "./specs"})
	if !debug {
		t.Fatal("expected debug to be true")
	}
	if path != "./specs" {
		t.Fatalf("path = %q, want ./specs", path)
	}
}

func TestBuildRecursive(t *testing.T) {
	tmpDir := t.TempDir()
	writeFile(t, filepath.Join(tmpDir, "example_test.dmj"), `package example_test

import "testing"

unit "hello" {
	then "works" {
		expect 1 == 1
	}
}
`)
	writeFile(t, filepath.Join(tmpDir, "nested", "service_test.dmj"), `package nested_test

import "testing"

unit "nested" {
	then "works" {
		expect true
	}
}
`)

	if err := build(tmpDir, false); err != nil {
		t.Fatalf("build: %v", err)
	}

	for _, outputFile := range []string{
		filepath.Join(tmpDir, "example_danmuji_test.go"),
		filepath.Join(tmpDir, "nested", "service_danmuji_test.go"),
	} {
		content, err := os.ReadFile(outputFile)
		if err != nil {
			t.Fatalf("read output %s: %v", outputFile, err)
		}
		if !strings.Contains(string(content), "Code generated by danmuji") {
			t.Fatalf("expected generated header in %s", outputFile)
		}
	}
}

func TestBuildRecursiveAggregatesErrors(t *testing.T) {
	tmpDir := t.TempDir()
	writeFile(t, filepath.Join(tmpDir, "good_test.dmj"), `package good_test

import "testing"

unit "good" {
	then "works" {
		expect true
	}
}
`)
	writeFile(t, filepath.Join(tmpDir, "bad_test.dmj"), `package bad_test

func helper() {
		expect
}
`)

	err := build(tmpDir, false)
	if err == nil {
		t.Fatal("expected build to report aggregated transpile errors")
	}
	if !strings.Contains(err.Error(), `expected expression after "expect"`) {
		t.Fatalf("unexpected error: %v", err)
	}
	if strings.Contains(err.Error(), ":1:1: expected expression after \"expect\"") {
		t.Fatalf("expected error to anchor near the invalid expect, got %v", err)
	}

	outputFile := filepath.Join(tmpDir, "good_danmuji_test.go")
	if _, statErr := os.Stat(outputFile); statErr != nil {
		t.Fatalf("expected successful file to still be generated: %v", statErr)
	}
}

func TestBuildSingleFile(t *testing.T) {
	tmpDir := t.TempDir()
	dmjPath := filepath.Join(tmpDir, "single.dmj")
	writeFile(t, dmjPath, `package single_test

import "testing"

unit "single" {
	then "ok" {
		expect true
	}
}
`)

	if err := build(dmjPath, false); err != nil {
		t.Fatalf("build: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(tmpDir, "single_danmuji_test.go"))
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	if !strings.Contains(string(content), "Code generated by danmuji") {
		t.Fatal("expected generated header")
	}
}

func TestRunTestCommandRecursive(t *testing.T) {
	tmpDir := newTestModule(t)
	writeFile(t, filepath.Join(tmpDir, "nested", "math.dmj"), `package nested_test

import "testing"

unit "addition" {
	then "one plus one" {
		expect 1+1 == 2
	}
}
`)

	if code := runTest([]string{tmpDir}); code != 0 {
		t.Fatalf("runTest returned %d", code)
	}

	generatedFile := filepath.Join(tmpDir, "nested", "math_danmuji_test.go")
	if _, err := os.Stat(generatedFile); !os.IsNotExist(err) {
		t.Fatalf("expected generated file %s to be cleaned up", generatedFile)
	}
}

func TestRunTestCommandSingleFile(t *testing.T) {
	tmpDir := newTestModule(t)
	dmjPath := filepath.Join(tmpDir, "multiply.dmj")
	writeFile(t, dmjPath, `package testpkg_test

import "testing"

unit "multiply two" {
	then "three times four" {
		expect 3*4 == 12
	}
}
`)

	if code := runTest([]string{dmjPath}); code != 0 {
		t.Fatalf("runTest returned %d", code)
	}

	generatedFile := filepath.Join(tmpDir, "multiply_danmuji_test.go")
	if _, err := os.Stat(generatedFile); !os.IsNotExist(err) {
		t.Fatal("expected generated file to be cleaned up")
	}
}

func TestRunTestNoFiles(t *testing.T) {
	tmpDir := t.TempDir()
	if code := runTest([]string{tmpDir}); code == 0 {
		t.Fatal("expected non-zero exit when no .dmj files exist")
	}
}

func TestBuildDebugFlag(t *testing.T) {
	tmpDir := t.TempDir()
	dmjPath := filepath.Join(tmpDir, "debug.dmj")
	writeFile(t, dmjPath, `package debug_test

import "testing"

unit "debug" {
	then "works" {
		expect 1 == 1
	}
}
`)

	if err := build(dmjPath, true); err != nil {
		t.Fatalf("build --debug: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(tmpDir, "debug_danmuji_test.go"))
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	if strings.Contains(string(content), "//line") {
		t.Fatal("expected no //line directives in debug mode output")
	}
}

// TestInitProjectAddsTestify creates a bare Go module in a temp dir, calls
// initProject, and asserts that testify is present in go.mod afterwards.
func TestInitProjectAddsTestify(t *testing.T) {
	tmpDir := t.TempDir()
	goMod := "module initpkgtest\n\ngo 1.24.0\n"
	if err := os.WriteFile(filepath.Join(tmpDir, "go.mod"), []byte(goMod), 0644); err != nil {
		t.Fatalf("write go.mod: %v", err)
	}

	if err := initProject(tmpDir); err != nil {
		t.Fatalf("initProject: %v", err)
	}

	modBytes, err := os.ReadFile(filepath.Join(tmpDir, "go.mod"))
	if err != nil {
		t.Fatalf("read go.mod after init: %v", err)
	}
	if !strings.Contains(string(modBytes), "github.com/stretchr/testify") {
		t.Fatalf("expected testify in go.mod after init, got:\n%s", modBytes)
	}

	sumBytes, err := os.ReadFile(filepath.Join(tmpDir, "go.sum"))
	if err != nil {
		t.Fatalf("read go.sum after init: %v", err)
	}
	if len(strings.TrimSpace(string(sumBytes))) == 0 {
		t.Fatal("expected go.sum to be non-empty after init")
	}
}

// TestInitProjectFailsLoudlyOnBadDir checks that initProject returns a non-nil
// error (not silently ignoring it) when the target directory does not contain
// a go.mod (so `go get` fails).
func TestInitProjectFailsLoudlyOnBadDir(t *testing.T) {
	// A directory with no go.mod — go get should fail.
	tmpDir := t.TempDir()
	err := initProject(tmpDir)
	if err == nil {
		t.Fatal("expected initProject to return an error for a dir without go.mod")
	}
}

// TestRunTestPreservesPreExistingGeneratedFile verifies that a committed
// in-tree _danmuji_test.go is NOT deleted after `danmuji test` completes,
// regardless of whether the test run itself passes or fails.
func TestRunTestPreservesPreExistingGeneratedFile(t *testing.T) {
	tmpDir := newTestModule(t)

	dmjPath := filepath.Join(tmpDir, "keep.dmj")
	writeFile(t, dmjPath, `package testpkg_test

import "testing"

unit "keep" {
	then "works" {
		expect 1 == 1
	}
}
`)

	// Pre-create the generated file (simulating a committed in-tree generated file).
	generatedPath := filepath.Join(tmpDir, "keep_danmuji_test.go")
	sentinel := "// pre-existing sentinel content\n"
	if err := os.WriteFile(generatedPath, []byte(sentinel), 0644); err != nil {
		t.Fatalf("write pre-existing generated file: %v", err)
	}

	// We call runTest and intentionally ignore the exit code — the grammar may
	// be stale in some envs (causing a go test compile error), but the cleanup
	// semantics must hold regardless of whether the tests pass.
	runTest([]string{dmjPath})

	// The generated file must still exist after the run.
	if _, err := os.Stat(generatedPath); os.IsNotExist(err) {
		t.Fatal("pre-existing generated file was deleted by danmuji test — it should be preserved")
	}
}

// TestRunTestCleansUpNewGeneratedFile ensures that a generated file that did
// NOT exist before the invocation is removed after `danmuji test`,
// regardless of whether the test run itself passes or fails.
func TestRunTestCleansUpNewGeneratedFile(t *testing.T) {
	tmpDir := newTestModule(t)

	dmjPath := filepath.Join(tmpDir, "new.dmj")
	writeFile(t, dmjPath, `package testpkg_test

import "testing"

unit "new" {
	then "works" {
		expect 2 == 2
	}
}
`)

	generatedPath := filepath.Join(tmpDir, "new_danmuji_test.go")
	// Ensure it does NOT exist before the run.
	os.Remove(generatedPath)

	// We call runTest and intentionally ignore the exit code (see above).
	runTest([]string{dmjPath})

	if _, err := os.Stat(generatedPath); !os.IsNotExist(err) {
		t.Fatal("newly-created generated file should have been cleaned up but still exists")
	}
}

func TestFmtDanmujiRecursive(t *testing.T) {
	tmpDir := t.TempDir()
	path := filepath.Join(tmpDir, "nested", "format_test.dmj")
	writeFile(t, path, `package main_test

import "testing"

unit "test" {
  given "a value" {
    x := 42
      then "it is 42" {
        expect x == 42
      }
  }
}
`)

	if err := fmtDanmuji(tmpDir); err != nil {
		t.Fatalf("fmtDanmuji: %v", err)
	}

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read formatted file: %v", err)
	}
	if !strings.Contains(string(content), "\t") {
		t.Fatal("expected tab indentation after formatting")
	}
}
