package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestDanmujiCLIBuild(t *testing.T) {
	// Create a temp dir with a .dmj file
	tmpDir := t.TempDir()
	dmjSource := `package example_test

import "testing"

unit "hello" {
	then "works" {
		expect 1 == 1
	}
}
`
	if err := os.WriteFile(filepath.Join(tmpDir, "example_test.dmj"), []byte(dmjSource), 0644); err != nil {
		t.Fatalf("write dmj file: %v", err)
	}

	// Build the CLI
	cliBin := filepath.Join(t.TempDir(), "danmuji")
	cmd := exec.Command("go", "build", "-o", cliBin, "./cmd/danmuji")
	cmd.Dir = "/home/draco/work/danmuji"
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("build CLI: %v\n%s", err, out)
	}

	// Run danmuji build on the temp dir
	cmd = exec.Command(cliBin, "build", tmpDir)
	out, err = cmd.CombinedOutput()
	t.Logf("danmuji build output:\n%s", string(out))
	if err != nil {
		t.Fatalf("danmuji build: %v\n%s", err, out)
	}

	// Check output file exists (example_test.dmj -> example_danmuji_test.go)
	outputFile := filepath.Join(tmpDir, "example_danmuji_test.go")
	if _, err := os.Stat(outputFile); err != nil {
		t.Fatalf("output file not found: %v", err)
	}

	// Verify it has the generated header
	content, err := os.ReadFile(outputFile)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	if !strings.Contains(string(content), "Code generated by danmuji") {
		t.Error("expected generated header in output file")
	}

	// Verify it contains the transpiled test function
	if !strings.Contains(string(content), "func TestHello(t *testing.T)") {
		t.Error("expected TestHello function in generated code")
	}
}

func TestDanmujiCLIBuildSingleFile(t *testing.T) {
	// Create a temp dir with a .dmj file
	tmpDir := t.TempDir()
	dmjSource := `package single_test

import "testing"

unit "single" {
	then "ok" {
		expect true
	}
}
`
	dmjPath := filepath.Join(tmpDir, "single.dmj")
	if err := os.WriteFile(dmjPath, []byte(dmjSource), 0644); err != nil {
		t.Fatalf("write dmj file: %v", err)
	}

	// Build the CLI
	cliBin := filepath.Join(t.TempDir(), "danmuji")
	cmd := exec.Command("go", "build", "-o", cliBin, "./cmd/danmuji")
	cmd.Dir = "/home/draco/work/danmuji"
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("build CLI: %v\n%s", err, out)
	}

	// Run danmuji build on a single file
	cmd = exec.Command(cliBin, "build", dmjPath)
	out, err = cmd.CombinedOutput()
	t.Logf("danmuji build output:\n%s", string(out))
	if err != nil {
		t.Fatalf("danmuji build: %v\n%s", err, out)
	}

	// Check output file exists (single.dmj -> single_danmuji_test.go)
	outputFile := filepath.Join(tmpDir, "single_danmuji_test.go")
	if _, err := os.Stat(outputFile); err != nil {
		t.Fatalf("output file not found: %v", err)
	}

	content, err := os.ReadFile(outputFile)
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	if !strings.Contains(string(content), "Code generated by danmuji") {
		t.Error("expected generated header")
	}
}

func TestDanmujiCLINoArgs(t *testing.T) {
	// Build the CLI
	cliBin := filepath.Join(t.TempDir(), "danmuji")
	cmd := exec.Command("go", "build", "-o", cliBin, "./cmd/danmuji")
	cmd.Dir = "/home/draco/work/danmuji"
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("build CLI: %v\n%s", err, out)
	}

	// Run with no args -- should fail with usage
	cmd = exec.Command(cliBin)
	out, err = cmd.CombinedOutput()
	if err == nil {
		t.Fatal("expected non-zero exit with no args")
	}
	if !strings.Contains(string(out), "Usage:") {
		t.Error("expected usage message in stderr")
	}
}
