// Package main implements the danmuji CLI tool that transpiles .dmj files
// to _danmuji_test.go files suitable for `go test`.
package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/odvcencio/danmuji"
)

const generatedHeader = "// Code generated by danmuji — DO NOT EDIT.\n\n"

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintf(os.Stderr, "Usage: danmuji <build|test> <path>\n")
		os.Exit(1)
	}

	switch os.Args[1] {
	case "build":
		debug, path := parseBuildArgs(os.Args[2:])
		if path == "" {
			fmt.Fprintf(os.Stderr, "Usage: danmuji build [--debug] <path>\n")
			os.Exit(1)
		}
		if err := build(path, debug); err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			os.Exit(1)
		}
	case "test":
		code := runTest(os.Args[2:])
		os.Exit(code)
	case "init":
		if err := initProject(); err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			os.Exit(1)
		}
	default:
		fmt.Fprintf(os.Stderr, "Unknown command: %s\nUsage: danmuji <build|test|init> <path>\n", os.Args[1])
		os.Exit(1)
	}
}

// parseBuildArgs extracts --debug flag and path from build arguments.
func parseBuildArgs(args []string) (debug bool, path string) {
	for _, arg := range args {
		if arg == "--debug" {
			debug = true
		} else if path == "" {
			path = arg
		}
	}
	return
}

// transpileFile transpiles a single .dmj file and writes the output .go file.
// Returns the path to the generated file.
func transpileFile(path string, opts danmuji.TranspileOptions) (string, error) {
	source, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read %s: %w", path, err)
	}

	absPath, _ := filepath.Abs(path)
	opts.SourceFile = absPath
	goCode, err := danmuji.TranspileDanmuji(source, opts)
	if err != nil {
		return "", fmt.Errorf("transpile %s: %w", path, err)
	}

	// Output: foo_test.dmj -> foo_danmuji_test.go
	base := strings.TrimSuffix(filepath.Base(path), ".dmj")
	outName := base + "_danmuji_test.go"
	// If base already ends with _test, don't double it
	if strings.HasSuffix(base, "_test") {
		outName = strings.TrimSuffix(base, "_test") + "_danmuji_test.go"
	}
	outPath := filepath.Join(filepath.Dir(path), outName)

	output := generatedHeader + goCode
	if err := os.WriteFile(outPath, []byte(output), 0644); err != nil {
		return "", fmt.Errorf("write %s: %w", outPath, err)
	}

	fmt.Printf("  %s -> %s\n", filepath.Base(path), outName)
	return outPath, nil
}

func build(path string, debug bool) error {
	info, err := os.Stat(path)
	if err != nil {
		return err
	}

	opts := danmuji.TranspileOptions{Debug: debug}
	if info.IsDir() {
		return buildDir(path, opts)
	}
	_, err = transpileFile(path, opts)
	return err
}

func buildDir(dir string, opts danmuji.TranspileOptions) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}

	count := 0
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".dmj") {
			continue
		}
		if _, err := transpileFile(filepath.Join(dir, entry.Name()), opts); err != nil {
			return err
		}
		count++
	}
	fmt.Printf("danmuji: transpiled %d file(s)\n", count)
	return nil
}

// runTest implements `danmuji test <path> [-- go-test-flags...]`.
// It transpiles .dmj files, runs `go test`, cleans up generated files, and
// returns the exit code from `go test`.
func runTest(args []string) int {
	// Split args at "--" to separate danmuji args from go test flags.
	var path string
	var goTestFlags []string
	dashDash := -1
	for i, arg := range args {
		if arg == "--" {
			dashDash = i
			break
		}
	}
	if dashDash >= 0 {
		goTestFlags = args[dashDash+1:]
		args = args[:dashDash]
	}
	if len(args) < 1 {
		fmt.Fprintf(os.Stderr, "Usage: danmuji test <path> [-- go-test-flags...]\n")
		return 1
	}
	path = args[0]

	// Discover .dmj files.
	var dmjFiles []string
	info, err := os.Stat(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return 1
	}
	if info.IsDir() {
		entries, err := os.ReadDir(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			return 1
		}
		for _, entry := range entries {
			if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".dmj") {
				dmjFiles = append(dmjFiles, filepath.Join(path, entry.Name()))
			}
		}
	} else {
		dmjFiles = append(dmjFiles, path)
	}

	if len(dmjFiles) == 0 {
		fmt.Fprintf(os.Stderr, "danmuji test: no .dmj files found at %s\n", path)
		return 1
	}

	// Transpile all .dmj files, collecting generated paths for cleanup.
	var generated []string
	for _, f := range dmjFiles {
		outPath, err := transpileFile(f, danmuji.TranspileOptions{})
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			cleanup(generated)
			return 1
		}
		generated = append(generated, outPath)
	}

	// Determine the directory to run `go test` in.
	testDir := path
	if !info.IsDir() {
		testDir = filepath.Dir(path)
	}

	// Run go test, streaming output to the terminal.
	goArgs := []string{"test"}
	goArgs = append(goArgs, goTestFlags...)
	goArgs = append(goArgs, ".")
	cmd := exec.Command("go", goArgs...)
	cmd.Dir = testDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	exitCode := 0
	if err := cmd.Run(); err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			exitCode = exitErr.ExitCode()
		} else {
			fmt.Fprintf(os.Stderr, "error running go test: %v\n", err)
			exitCode = 1
		}
	}

	// Clean up generated files regardless of pass/fail.
	cleanup(generated)
	return exitCode
}

// cleanup removes the given list of generated files, logging any errors.
func cleanup(files []string) {
	for _, f := range files {
		if err := os.Remove(f); err != nil && !os.IsNotExist(err) {
			fmt.Fprintf(os.Stderr, "warning: failed to clean up %s: %v\n", f, err)
		}
	}
}

// initProject adds testify to the current module.
func initProject() error {
	get := exec.Command("go", "get", "github.com/stretchr/testify@latest")
	get.Stdout = os.Stdout
	get.Stderr = os.Stderr
	if err := get.Run(); err != nil {
		return fmt.Errorf("go get testify: %w", err)
	}

	tidy := exec.Command("go", "mod", "tidy")
	tidy.Stdout = os.Stdout
	tidy.Stderr = os.Stderr
	if err := tidy.Run(); err != nil {
		return fmt.Errorf("go mod tidy: %w", err)
	}

	fmt.Println("danmuji: testify added. You're ready to write .dmj files.")
	return nil
}
