package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

var sharedTestModuleDir string

func TestMain(m *testing.M) {
	dir, err := prepareSharedTestModule()
	if err != nil {
		fmt.Fprintf(os.Stderr, "prepare shared test module: %v\n", err)
		os.Exit(1)
	}
	sharedTestModuleDir = dir

	code := m.Run()
	_ = os.RemoveAll(dir)
	os.Exit(code)
}

func prepareSharedTestModule() (string, error) {
	tmpDir, err := os.MkdirTemp("", "danmuji-cli-testmod-")
	if err != nil {
		return "", err
	}

	goMod := `module testpkg

go 1.24.0

require github.com/stretchr/testify v1.9.0
`
	if err := os.WriteFile(filepath.Join(tmpDir, "go.mod"), []byte(goMod), 0644); err != nil {
		return "", err
	}

	placeholder := `package testpkg_test

import _ "github.com/stretchr/testify/assert"
`
	placeholderPath := filepath.Join(tmpDir, "placeholder_test.go")
	if err := os.WriteFile(placeholderPath, []byte(placeholder), 0644); err != nil {
		return "", err
	}

	cmd := exec.Command("go", "mod", "tidy")
	cmd.Dir = tmpDir
	if out, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("go mod tidy: %w\n%s", err, out)
	}

	if err := os.Remove(placeholderPath); err != nil {
		return "", err
	}
	return tmpDir, nil
}

func newTestModule(t *testing.T) string {
	t.Helper()
	tmpDir := t.TempDir()
	for _, name := range []string{"go.mod", "go.sum"} {
		data, err := os.ReadFile(filepath.Join(sharedTestModuleDir, name))
		if err != nil {
			t.Fatalf("read shared %s: %v", name, err)
		}
		if err := os.WriteFile(filepath.Join(tmpDir, name), data, 0644); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}
	return tmpDir
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatalf("mkdir %s: %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func TestParseBuildArgs(t *testing.T) {
	debug, path := parseBuildArgs([]string{"--debug", "./specs"})
	if !debug {
		t.Fatal("expected debug to be true")
	}
	if path != "./specs" {
		t.Fatalf("path = %q, want ./specs", path)
	}
}

func TestBuildRecursive(t *testing.T) {
	tmpDir := t.TempDir()
	writeFile(t, filepath.Join(tmpDir, "example_test.dmj"), `package example_test

import "testing"

unit "hello" {
	then "works" {
		expect 1 == 1
	}
}
`)
	writeFile(t, filepath.Join(tmpDir, "nested", "service_test.dmj"), `package nested_test

import "testing"

unit "nested" {
	then "works" {
		expect true
	}
}
`)

	if err := build(tmpDir, false); err != nil {
		t.Fatalf("build: %v", err)
	}

	for _, outputFile := range []string{
		filepath.Join(tmpDir, "example_danmuji_test.go"),
		filepath.Join(tmpDir, "nested", "service_danmuji_test.go"),
	} {
		content, err := os.ReadFile(outputFile)
		if err != nil {
			t.Fatalf("read output %s: %v", outputFile, err)
		}
		if !strings.Contains(string(content), "Code generated by danmuji") {
			t.Fatalf("expected generated header in %s", outputFile)
		}
	}
}

func TestBuildSingleFile(t *testing.T) {
	tmpDir := t.TempDir()
	dmjPath := filepath.Join(tmpDir, "single.dmj")
	writeFile(t, dmjPath, `package single_test

import "testing"

unit "single" {
	then "ok" {
		expect true
	}
}
`)

	if err := build(dmjPath, false); err != nil {
		t.Fatalf("build: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(tmpDir, "single_danmuji_test.go"))
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	if !strings.Contains(string(content), "Code generated by danmuji") {
		t.Fatal("expected generated header")
	}
}

func TestRunTestCommandRecursive(t *testing.T) {
	tmpDir := newTestModule(t)
	writeFile(t, filepath.Join(tmpDir, "nested", "math.dmj"), `package nested_test

import "testing"

unit "addition" {
	then "one plus one" {
		expect 1+1 == 2
	}
}
`)

	if code := runTest([]string{tmpDir}); code != 0 {
		t.Fatalf("runTest returned %d", code)
	}

	generatedFile := filepath.Join(tmpDir, "nested", "math_danmuji_test.go")
	if _, err := os.Stat(generatedFile); !os.IsNotExist(err) {
		t.Fatalf("expected generated file %s to be cleaned up", generatedFile)
	}
}

func TestRunTestCommandSingleFile(t *testing.T) {
	tmpDir := newTestModule(t)
	dmjPath := filepath.Join(tmpDir, "multiply.dmj")
	writeFile(t, dmjPath, `package testpkg_test

import "testing"

unit "multiply two" {
	then "three times four" {
		expect 3*4 == 12
	}
}
`)

	if code := runTest([]string{dmjPath}); code != 0 {
		t.Fatalf("runTest returned %d", code)
	}

	generatedFile := filepath.Join(tmpDir, "multiply_danmuji_test.go")
	if _, err := os.Stat(generatedFile); !os.IsNotExist(err) {
		t.Fatal("expected generated file to be cleaned up")
	}
}

func TestRunTestNoFiles(t *testing.T) {
	tmpDir := t.TempDir()
	if code := runTest([]string{tmpDir}); code == 0 {
		t.Fatal("expected non-zero exit when no .dmj files exist")
	}
}

func TestBuildDebugFlag(t *testing.T) {
	tmpDir := t.TempDir()
	dmjPath := filepath.Join(tmpDir, "debug.dmj")
	writeFile(t, dmjPath, `package debug_test

import "testing"

unit "debug" {
	then "works" {
		expect 1 == 1
	}
}
`)

	if err := build(dmjPath, true); err != nil {
		t.Fatalf("build --debug: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(tmpDir, "debug_danmuji_test.go"))
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	if strings.Contains(string(content), "//line") {
		t.Fatal("expected no //line directives in debug mode output")
	}
}

func TestFmtDanmujiRecursive(t *testing.T) {
	tmpDir := t.TempDir()
	path := filepath.Join(tmpDir, "nested", "format_test.dmj")
	writeFile(t, path, `package main_test

import "testing"

unit "test" {
  given "a value" {
    x := 42
      then "it is 42" {
        expect x == 42
      }
  }
}
`)

	if err := fmtDanmuji(tmpDir); err != nil {
		t.Fatalf("fmtDanmuji: %v", err)
	}

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read formatted file: %v", err)
	}
	if !strings.Contains(string(content), "\t") {
		t.Fatal("expected tab indentation after formatting")
	}
}
